#'@name generate_active_days
#'@title Generates a \link{tibble} of active days
#'@param year year
#'@param month month
#'@param fishing_units one or more fishing unit(s)
#'@return an object of class \link{tibble} give active days
generate_active_days = function(year, month, fishing_units){
  tibble::tibble(
    year = year, 
    month = month,
    fishing_unit = fishing_units,
    effort_fishable_duration = lubridate::days_in_month(ISOdate(year, month, 1))
  )
}

#'@name complete_active_days
#'@title Complete the active days.
#'@description If it is set to zero or or is NA, the nb of active days
#'in the period will be autogenerated
#'@param active_days active days object of class \link{tibble}
#'@return the curated active days table
#'@export
complete_active_days = function(active_days){
  active_days$effort_fishable_duration <- sapply(1:nrow(active_days), function(i){
    row = active_days[i,]
    out = row$effort_fishable_duration
    if(is.na(out)|out == 0){
      out = lubridate::days_in_month(ISOdate(row$year, row$month, 1))
    }
    return(out)
  })
  return(active_days)
}