#'@name generate_active_days_by_period
#'@title Generates a \link{tibble} of active days.
#'@description Function that generates a table of active days by year/month. The unique list
#'of fishing units are inherited from available tables (active_vessels, effort, landings). In
#'the same way, the list of minor strata values will be inherited based on the minor_strata
#'columns available in data.
#'
#'@param year year
#'@param month month
#'@param active_vessels active vessels table
#'@param effort effort table
#'@param effort_source effort source 
#'@param landings landings table
#'@param minor_strata minor strata. Default is \code{NULL}
#'@return an object of class \link{tibble} give active days
#'@export
generate_active_days_by_period = function(year, month, 
                                active_vessels,
                                effort,
                                effort_source = c("fisher_interview", "boat_counting"),
                                landings,
                                minor_strata = NULL){
  
  effort_source = match.arg(effort_source)
  
  mapping_landing_site_zone = NULL
  
  get_unique_values = function(column,active_vessels,effort,landings){
    values = unique(c(
      as.data.frame(active_vessels)[,column], 
      as.data.frame(effort)[,column], 
      as.data.frame(landings)[,column]
    ))
    values = values[!is.na(values)]
    return(values)
  }
  
  #autogenerate active_days table
  fishing_unit_values = get_unique_values("fishing_unit", active_vessels, effort, landings)
  dims = list(fishing_unit = fishing_unit_values)
  if(!is.null(minor_strata)){
    minor_strata_values = lapply(minor_strata, function(x){
      get_unique_values(x, active_vessels, effort, landings)
    })
    names(minor_strata_values) = minor_strata
    dims = minor_strata_values
    dims$fishing_unit = fishing_unit_values
  }
  if(effort_source == "boat_counting") if("landing_site" %in% colnames(active_vessels)){
    dims$landing_site = get_unique_values("landing_site", active_vessels, effort, landings)
    if(!is.null(minor_strata)) if(regexpr("zone", minor_strata) > 0){
      mapping_landing_site_zone = unique(rbind(
        as.data.frame(active_vessels)[,c("landing_site","zone")], 
        as.data.frame(effort)[,c("landing_site","zone")], 
        as.data.frame(landings)[,c("landing_site","zone")]
      ))
      mapping_landing_site_zone = mapping_landing_site_zone[!is.na(mapping_landing_site_zone$zone)&!is.na(mapping_landing_site_zone$landing_site),]
    }
  }
  
  out = tibble::tibble(
    year = year, 
    month = month,
    expand.grid(dims),
    effort_fishable_duration = lubridate::days_in_month(ISOdate(year, month, 1))
  )
  if(!is.null(mapping_landing_site_zone)){
    out = out %>%
      dplyr::right_join(mapping_landing_site_zone)
  }
  out = out[!is.na(out$effort_fishable_duration),]
  return(out)
}

#'@name generate_active_days
#'@title Generates a \link{tibble} of active days.
#'@description Function that generates a table of active days for all periods. The unique list
#'of fishing units are inherited from available tables (active_vessels, effort, landings). In
#'the same way, the list of minor strata values will be inherited based on the minor_strata
#'columns available in data.
#'
#'@param active_vessels active vessels table
#'@param effort effort table
#'@param effort_source effort source
#'@param landings landings table
#'@param minor_strata minor strata. Default is \code{NULL}
#'@return an object of class \link{tibble} give active days
#'@export
generate_active_days = function(active_vessels,
                                effort,
                                effort_source,
                                landings,
                                minor_strata = NULL){
 
  periods = unique(rbind(effort[,c("year","month")], landings[,c("year","month")]))
  if("year" %in% colnames(active_vessels) & "month" %in% colnames(active_vessels)){
    periods = unique(rbind(periods, active_vessels[,c("year","month")]))
  }
  
  do.call("rbind", lapply(1:nrow(periods), function(i){
    year = periods[i,]$year
    month = periods[i,]$month
    generate_active_days_by_period(
      year = year, month = month,
      active_vessels = {
        if("year" %in% colnames(active_vessels) & "month" %in% colnames(active_vessels)){
          active_vessels[active_vessels$year == year & active_vessels$month == month,]
        }else{
          active_vessels
        }
      },
      effort = effort[effort$year == year & effort$month == month,],
      effort_source = effort_source,
      landings = landings[landings$year == year & landings$month == month,],
      minor_strata = minor_strata
    )
  })) 
  
}

#'@name complete_active_days
#'@title Complete the active days.
#'@description If it is set to zero or or is NA, the nb of active days
#'in the period will be autogenerated
#'@param active_days active days object of class \link{tibble}
#'@return the curated active days table
#'@export
complete_active_days = function(active_days){
  active_days$effort_fishable_duration <- sapply(1:nrow(active_days), function(i){
    row = active_days[i,]
    out = row$effort_fishable_duration
    if(is.na(out)|out == 0){
      out = lubridate::days_in_month(ISOdate(row$year, row$month, 1))
    }
    return(out)
  })
  return(active_days)
}